name: Stackspot workflow dispatch
run-name: ${{ inputs.correlation_id }}
on: 
  workflow_call:
    inputs:
      correlation_id:
        description: Correlation id
        required: true
        type: string
      workflow_name:
        description: Workflow path
        required: true
        type: string
      secrets:
        description: Secrets info (json)
        required: true
        type: string
      api_inputs:
        description: Workflow inputs (json)
        required: true
        type: string
jobs:
  redirect:
    uses: fernandochagaszup/workflow-stk-edp/.github/workflows/middle-flow.yml@main
    with:
      api_inputs: ${{ github.event.inputs.api_inputs }}
      workflow_name: ${{ github.event.inputs.workflow_name }}
      correlation_id: ${{ github.event.inputs.correlation_id }}
      config: "{
        \"runner\": \"ubuntu-latest\",
        \"github_org\": \"${{ github.repository_owner }}\",
        \"debug\": false,
        \"stk\": \"stk\",
        \"origin_repository\": \"fernandochagaszup/workflow-stk-edp\",
        \"origin_branch\": \"main\",
        \"default_branch\": \"main\"
        }"
    secrets:
      secrets: ${{ github.event.inputs.secrets }}