name: Stackspot workflow dispatch
run-name: ${{ inputs.correlation_id }}
on: 
  workflow_dispatch:
    inputs:
      correlation_id:
        description: Correlation id
        required: true
      workflow_name:
        description: Workflow path
        required: true
      secrets:
        description: Secrets info (json)
        required: true
      api_inputs:
        description: Workflow inputs (json)
        required: true
jobs:
  redirect:
    uses: fernandochagaszup/workflow-stk-edp/.github/workflows/workflow_reutilizavel.yml@main
    with:
      api_inputs: ${{ github.event.inputs.api_inputs }}
      workflow_name: ${{ github.event.inputs.workflow_name }}
      correlation_id: ${{ github.event.inputs.correlation_id }}
    secrets:
      secrets: ${{ github.event.inputs.secrets }}