name: Stackspot reusable workflow
run-name: ${{ inputs.correlation_id }}
on: 
  workflow_call:
    inputs:
      correlation_id:
        description: Correlation id
        required: true
        type: string
      workflow_name:
        description: Workflow path
        required: true
        type: string
      secrets:
        description: Secrets info (json)
        required: true
        type: string
      api_inputs:
        description: Workflow inputs (json)
        required: true
        type: string
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Primeiro passo
        run: |
          echo "Correlation ID: ${{ inputs.correlation_id }}"
          echo "Workflow Name: ${{ inputs.workflow_name }}"
          echo "Secrets: ${{ inputs.secrets }}"
          echo "API Inputs: ${{ inputs.api_inputs }}"
          echo "This is an example step."