name: Stackspot reusable workflow
run-name: RW-${{ inputs.correlation_id }}
on: 
  workflow_call:
    inputs:
      correlation_id:
        description: Correlation id
        required: true
        type: string
      workflow_name:
        description: Workflow path
        required: true
        type: string
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Primeiro passo
        run: |
          echo "Correlation ID: ${{ inputs.correlation_id }}"
          echo "Workflow Name: ${{ inputs.workflow_name }}"
          echo "This is an example step."
